name: Build Firefox Extension
on:
  push:
    branches: [ main ]
  release:
    types: [created, published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build XPI
      run: |
        mkdir -p web-ext-artifacts
        cd $(pwd)
        zip -r web-ext-artifacts/artelier-tab.xpi \
          manifest.json \
          src/html/* \
          src/css/* \
          src/js/* \
          src/lib/* \
          --exclude "*.git*" \
          --exclude "*.DS_Store"
    
    - name: Upload to Release
      if: github.event_name == 'release'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release upload ${{ github.event.release.tag_name }} web-ext-artifacts/artelier-tab.xpi --clobber
    
    - name: Upload as Artifact
      if: github.event_name == 'push'
      uses: actions/upload-artifact@v4
      with:
        name: extension
        path: web-ext-artifacts/artelier-tab.xpi
        if-no-files-found: error
